name: publish
on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: upload
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: i18n
          path: dist
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: i18n
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: publish
        run: npm publish --access public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: i18n
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: publish
        run: npm publish
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
